CUDA_VISIBLE_DEVICES=0 python -m main.main --dataset=tut-urban-acoustic-scenes-2018 \
    --data-root="/home/wakamatsu/DataSets3/TUT/TUT-urban-acoustic-scenes-2018-development" \
    --domain_group=0 --n_task=6 --model=udil --lr=1e-3 \
    --incremental-lr=1e-3 \
    --reset-training-state-per-task \
    --scheduler=cosine_annealing \
    --T_max=120 \
    --eta_min=1e-5 \
    --incremental-scheduler=same \
    --n-epochs=120 --batch-size=128 --buffer-size=200 --buffer-batch-size=64 \
    --backbone=resnet18 \
    --discriminator=mnistmlp --disc-num-layers=4 --loss=ce --disc-k=1 --disc-lr=1e-5 \
    --task-weight-k=1 --task-weight-lr=2e-3 --loop-k=1 --eval-protocol=domain-agnostic --epoch-scaling=const --C=100 \
    --visualize --checkpoint --encoder-lambda=0.5 --num-workers=8 --encoder-mu=1 \
    --opt=adam --loss-form=sum --seed=1208 --supcon-lambda=0.01 --supcon-temperature=0.07 \
    --kd-threshold=1 --supcon-sim=l2 --supcon-first-domain --wandb-name=TUT-UDIL \
    --hop_size=512 \
    --is_audio=True
