CUDA_VISIBLE_DEVICES=0  python -m main.main --dataset=vgg-fsd50k-dcase \
    --domain_group=0 \
    --data-root="/home/wakamatsu/DataSets2/FSD_VGG_DCASE" \
    --n_task=4 \
    --model=adil \
    --lr=1e-4 \
    --incremental-lr=1e-4 \
    --reset-training-state-per-task \
    --scheduler="cosine_annealing" \
    --n-epochs=100 \
    --batch-size=128 \
    --backbone=resnet18_ds_bn_cl \
    --loss=ce \
    --eval-protocol=domain-agnostic \
    --epoch-scaling=const \
    --visualize \
    --checkpoint \
    --num-workers=8 \
    --opt=adam \
    --seed=1997 \
    --incremental-bn-init=d1 \
    --wandb-name=Librispeech-FINETUNE \
    --is_audio=True