CUDA_VISIBLE_DEVICES=0 python -m main.main --dataset=vgg-fsd50k-dcase \
    --domain_group=0 --data-root="/home/wakamatsu/DataSets2/FSD_VGG_DCASE" \
    --model=der --lr=1e-4 --incremental-lr=1e-4 \
    --reset-training-state-per-task \
    --scheduler="cosine_annealing" \
    --T_max=100 \
    --eta_min=1e-5 \
    --incremental-scheduler=same \
    --n-epochs=100 --batch-size=128 --backbone=resnet18 \
    --loss=ce --eval-protocol=domain-agnostic --epoch-scaling=const --alpha=0.5 --beta=0.5\
    --visualize --checkpoint --num-workers=8 \
    --buffer-size=180 --buffer-batch-size=64\
    --opt=adam --seed=1997 --wandb-name=Librispeech-DER \
    --is_audio=True
